name: "Deploy staging"
on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: "The branch, tag or SHA to checkout"
        required: true
        default: "main"

jobs:
  build_and_deploy:
    if: ${{ github.event.repository.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          ref: "${{ github.event.inputs.ref }}"
      - name: "Enable yarn cache"
        uses: c-hive/gha-yarn-cache@d528cd63c28aed0a9f44b1cada95050d7aa95c2e # v2  # using cache

      - name: "Setup node@14"
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 16

      - name: "Install dependencies"
        run: |
          yarn set version 3.1.1
          yarn install
      - name: "Deploy target: rinkeby-staging"
        run: yarn run docs:build

      - name: "Copy 404"
        run: |
          cp ./dist/docs/404.html ./dist/404.html

      - uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AQWZX_ZKSYNC_V2_DOCS }}"
          target: staging
          projectId: aqwzx-zksync-v2-docs
          channelID: live
